### ISSUE TITLE
lineage 16 (20190720) broke twrp 3.3.0-0 on sailfish mounting encrypted data, twrp 3.3.1 fixed it, but build is missing for sailfish

### ISSUE THREAD

**Issue by wuxxin** [TeamWin/android_device_google_sailfish#4]
repoduction:
+ update sailfish device to lineage 16 (20190720) 
+ twrp 3.3.0 can not mount encrypted data, and fails to flash nanodroid (microg, fdroid and friends)

additional:
+ i tried to download a newer version (3.3.1*) from jenkins.twrp.me, but there is no build for sailfish
+ i looked up marlin (pixel XL) which has a build job, and from what i looked up, 
https://github.com/TeamWin/android_device_google_marlin has support for both marlin and sailfish.

question:
+ How can i help to get twrp 3.3.1 build for sailfish ?
+ how can i build twrp 3.3.1 for sailfish myself, should i use the marlin repo and if so, how can i use the marlin repo but build sailfish twrp ?

Thank you for your work, 
best regards,
   Felix

**Comment by paravz** [comment]
echoing @wuxxin about the source of`twrp-3.3.0-0-sailfish.img` - is it built from this repo or from TeamWin/android_device_google_marlin, where there is a sailfish target: https://github.com/TeamWin/android_device_google_marlin/blob/lineage-16.0/aosp_sailfish.mk

**Comment by paravz** [comment]
previous version `twrp-3.2.3-1-sailfish.img`  doesn't decrypt the latest lineage (July 5 2019 patch level) as well

**Comment by wuxxin** [comment]
@bigbiff if there is anything where i can help,
or if you know how to build sailfish twrp 3.3.1,
please tell us :-)

**Comment by bigbiff** [comment]
Can you see if http://build.twrp.me/twrp-3.3.1-0-sailfish.img is horribly broken?

**Comment by wuxxin** [comment]
i think its working, i was able to
+ boot the build using 'fastboot boot twrp-3.3.1-0-sailfish.img`
+ decrypted datastorage using password
+ adb sideload nanodroid 
and on the next boot the system looks like it should :smile: , thanks

**Comment by paravz** [comment]
same here - thank you!
decrypt worked, i tested delete of backup - worked. i think there is a circular loop `/system/etc -> /system/etc` that doesn't seem to affect basic functionality, ie these are the messages upon booting and successful decrypting:
```
e4crypt_prepare_user_storage for volume null, user 0, serial 0, flags 1
Preparing: /data/system/users/0
Preparing: /data/misc/profiles/cur/0
Preparing: /data/system_de/0
Preparing: /data/misc_de/0
Preparing: /data/vendor_de/0
Preparing: /data/user_de/0
contents mode 'ice' filenames 'aes-256-cts'
not actually forking for vold_prepare_subdirs
Decrypted Successfully!
Data successfully decrypted
Updating partition details...
WARNING: linker: Warning: couldn't read "/system/etc/ld.config.txt" for "/sbin/sh" (using default configuration instead): error reading file "/system/etc/ld.config.txt": Too many symbolic links encountered
WARNING: linker: Warning: couldn't read "/system/etc/ld.config.txt" for "/sbin/toybox" (using default configuration instead): error reading file "/system/etc/ld.config.txt": Too many symbolic links encountered
I:mount -o bind '/data/media/0' '/sdcard' process ended with RC=0
```

btw aosp_sailfish.mk i mentioned is not in use and can be deleted

**Comment by paravz** [comment]
since this is open, another issue with 3.3.1 on sailfish regarding /system:

Advanced Wipe > System doesn't work on 3.3.1, works on 3.2.3.

3.3.1 wipe produces a message:
```
mke2fs -t ext4 -b 4096 /dev/block/bootdevice/by-name/system_b 524288 process ended with ERROR:1
Unable to wipe System
Unable to wipe /system
```
The problem seems to be that /system is mounted in 3.3.1 as `/s` even after explicitly unmounting it in the interface.
```
sailfish:/ # mount | grep sda34
/dev/block/sda34 on /s type ext4 (ro,seclabel,relatime,data=ordered)
sailfish:/ # ls -la /dev/block/bootdevice/by-name/system*
lrwxrwxrwx 1 root root 38 1970-01-29 07:01 /dev/block/bootdevice/by-name/system -> /dev/block/bootdevice/by-name/system_b
lrwxrwxrwx 1 root root 16 1970-01-29 07:00 /dev/block/bootdevice/by-name/system_a -> /dev/block/sda33
lrwxrwxrwx 1 root root 16 1970-01-29 07:00 /dev/block/bootdevice/by-name/system_b -> /dev/block/sda34
```

If i explicitly `umount /s` via adb shell in twrp, wiping /system succeeds.

**Comment by paravz** [comment]
this also means that installing lineage os on sailfish with latest twrp will fail for most people, as it calls for wiping /system: https://wiki.lineageos.org/devices/sailfish/install

**Comment by tarvcode** [comment]
Tried testing 3.3.1-0 on SAILFISH just running stock OS.  The passcode now works to decrypt the partition.  Tried to run the Magisk uninstaller and it threw two errors;
```
Updating partition details...
Failed to mount '/system' (Device or resource busy)
Failed to mount '/vendor' (Device or resource busy)
...done
```
Tried the same on 3.3.0-0, working with no errors.

**Comment by paravz** [comment]
@tarvcode while booted to twrp, try: `adb shell` and then:
`umount /s; umount /v; umount /system`
zip installs should now work . i tried opengapps

**Comment by TheArkive** [comment]
> 
> 
> same here - thank you!
> decrypt worked, i tested delete of backup - worked. i think there is a circular loop `/system/etc -> /system/etc` that doesn't seem to affect basic functionality, ie these are the messages upon booting and successful decrypting:
> 
> ```
> e4crypt_prepare_user_storage for volume null, user 0, serial 0, flags 1
> Preparing: /data/system/users/0
> Preparing: /data/misc/profiles/cur/0
> Preparing: /data/system_de/0
> Preparing: /data/misc_de/0
> Preparing: /data/vendor_de/0
> Preparing: /data/user_de/0
> contents mode 'ice' filenames 'aes-256-cts'
> not actually forking for vold_prepare_subdirs
> Decrypted Successfully!
> Data successfully decrypted
> Updating partition details...
> WARNING: linker: Warning: couldn't read "/system/etc/ld.config.txt" for "/sbin/sh" (using default configuration instead): error reading file "/system/etc/ld.config.txt": Too many symbolic links encountered
> WARNING: linker: Warning: couldn't read "/system/etc/ld.config.txt" for "/sbin/toybox" (using default configuration instead): error reading file "/system/etc/ld.config.txt": Too many symbolic links encountered
> I:mount -o bind '/data/media/0' '/sdcard' process ended with RC=0
> ```
> 
> btw aosp_sailfish.mk i mentioned is not in use and can be deleted

I get those errors too, but they don't consistently come up for me.  I usually see those errors after I try to mount /system.

**Comment by DiThi** [comment]
I can't decrypt with pattern with Android 10 (OTA update) on sailfish. TWRP was never installed, I always run it with fastboot. TWRP says it's incorrect pattern.

Tried latest (3.3.0-0) which seems old compared to marlin.

**Comment by wuxxin** [comment]
latest from main webpage:  https://eu.dl.twrp.me/sailfish/twrp-3.3.1-0-sailfish.img.html
which is binary identical with the jenkins build (https://jenkins.twrp.me/job/sailfish-prod/1/consoleFull):
https://build.twrp.me/twrp-3.3.1-0-sailfish.img

also, at least the jenkins version is build from the marlin tree, output from build log:
```
https://github.com/TeamWin/android_device_google_marlin.git
 > git checkout -b lineage-16.0 1a09bb197f5ba8e54df4fc31a2a8c565e9140808
```

**Comment by DiThi** [comment]
Sorry, yes, that one (3.3.1-0) is the one I've tried and no dice. It's from August and I guess the encryption scheme changed in September.
